name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Fetch private vault
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alex-ahr'
          repository: 'vault'
          access-token: ${{ secrets.PERSONAL_KEY }}
      
      - name: Clean up cloned files
        run: |
          # hardcoded for now
          rm -rf vault/.git
          rm -rf vault/templates
          mv vault content/

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: alex-ahr.github.io/quartz
